$(function(){
	/******************************注册背景颜色改变******************************/
	$("#headerOneReg").hover(function(){
		$(this).css("background-color","#676767");
	},function(){
		$(this).css("background-color","#434343");
	});
	/******************************注册背景颜色改变******************************/
	/******************************环球下拉列表******************************/
	$("#headerOneHuanqiu").hover(function(){
		$(this).find("img").attr("src","img/LogoTexiao2.png");
		$("#headerOneTeXiao").show();
	},function(){
		$(this).find("img").attr("src","img/LogoTexiao1.png");
		$("#headerOneTeXiao").hide();
	})
	$("#headerOneTeXiao").hover(function(){
		$("#headerOneHuanqiu").find("img").attr("src","img/LogoTexiao2.png");
		$("#headerOneTeXiao").show();
	},function(){
		$("#headerOneHuanqiu").find("img").attr("src","img/LogoTexiao1.png");
		$("#headerOneTeXiao").hide();
	})
	$("#headerOneTeXiao").click()
	/******************************环球下拉列表******************************/
	/******************************主特效******************************/
	var nanmeiWidth = $(".North_America").width();
	var nanmeiWidth = $(".North_America").height();
	$(".North_America").click(function(){                   //圆形点击事件
	    $(".South_America").hide();
	    $(".Europe").hide();
	    $(".Africa").hide();
	    $(".Asia").hide();
	    $(".Oceania").hide();
		$(".mudi_city").show();
		$(".mudi_city_ul").eq(0).fadeIn(450);
		$(".North_America").animate({					
            "top":"100px",					
            "left":"450px"				
        },450);
	})
	$(".South_America").click(function(){
	    $(".North_America").hide();
	    $(".Europe").hide();
	    $(".Africa").hide();
	    $(".Asia").hide();
	    $(".Oceania").hide();
		$(".mudi_city").show();
		$(".mudi_city_ul").eq(1).fadeIn(450);
		$(".South_America").animate({					
            "top":"100px",					
            "left":"450px"				
        },450);
	})
	$(".Europe").click(function(){
	    $(".South_America").hide();
	    $(".North_America").hide();
	    $(".Africa").hide();
	    $(".Asia").hide();
	    $(".Oceania").hide();
		$(".mudi_city").show();
		$(".mudi_city_ul").eq(2).fadeIn(450);
		$(".Europe").animate({					
            "top":"100px",					
            "left":"450px"				
        },450);
	})
    $(".Africa").click(function(){
	    $(".South_America").hide();
	    $(".Europe").hide();
	    $(".North_America").hide();
	    $(".Asia").hide();
	    $(".Oceania").hide();
		$(".mudi_city").show();
		$(".mudi_city_ul").eq(3).fadeIn(450);
		$(".Africa").animate({					
            "top":"100px",					
            "left":"450px"				
        },450);
	})
	$(".Asia").click(function(){
	    $(".South_America").hide();
	    $(".Europe").hide();
	    $(".Africa").hide();
	    $(".North_America").hide();
	    $(".Oceania").hide();
		$(".mudi_city").show();
		$(".mudi_city_ul").eq(4).fadeIn(450);
		$(".Asia").animate({					
            "top":"100px",					
            "left":"450px"				
        },450);
	})
	$(".Oceania").click(function(){
	    $(".South_America").hide();
	    $(".Europe").hide();
	    $(".Africa").hide();
	    $(".Asia").hide();
	    $(".North_America").hide();
		$(".mudi_city").show();
		$(".mudi_city_ul").eq(5).fadeIn(450);
		$(".Oceania").animate({					
            "top":"100px",					
            "left":"450px"				
        },450);
	})
	
	
    $(".close_box_btn").eq(0).click(function(event){
    	    $(".South_America").fadeIn(450);
	        $(".Europe").fadeIn(450);
	        $(".Africa").fadeIn(450);
	        $(".Asia").fadeIn(450);
	        $(".Oceania").fadeIn(450);
		    $(".mudi_city").hide();
		    $(".mudi_city_ul").eq(0).fadeOut(450);
		    $(".North_America").animate({					
                "top":"189px",					
                "left":"115px"				
            },450);
            event.stopPropagation()
    })
    $(".close_box_btn").eq(1).click(function(event){
      	    	$(".North_America").fadeIn(450);
	        $(".Europe").fadeIn(450);
	        $(".Africa").fadeIn(450);
	        $(".Asia").fadeIn(450);
	        $(".Oceania").fadeIn(450);
		    $(".mudi_city").hide();
		    $(".mudi_city_ul").eq(1).fadeOut(450);
		    $(".South_America").animate({					
                "top":"339px",					
                "left":"287px"				
            },450);
            event.stopPropagation()
    })
    $(".close_box_btn").eq(2).click(function(event){
      	    $(".North_America").fadeIn(450);
	        $(".South_America").fadeIn(450);
	        $(".Africa").fadeIn(450);
	        $(".Asia").fadeIn(450);
	        $(".Oceania").fadeIn(450);
		    $(".mudi_city").hide();
		    $(".mudi_city_ul").eq(2).fadeOut(450);
		    $(".Europe").animate({					
                "top":"166px",					
                "left":"469px"				
            },450);
            event.stopPropagation()
    })
    $(".close_box_btn").eq(3).click(function(event){
        	    	$(".North_America").fadeIn(450);
	        $(".South_America").fadeIn(450);
	        $(".Europe").fadeIn(450);
	        $(".Asia").fadeIn(450);
	        $(".Oceania").fadeIn(450);
		    $(".mudi_city").hide();
		    $(".mudi_city_ul").eq(3).fadeOut(450);
		    $(".Africa").animate({					
                "top":"301px",					
                "left":"470px"				
            },450);
            event.stopPropagation()
    })
    $(".close_box_btn").eq(4).click(function(event){
        	    	$(".North_America").fadeIn(450);
	        $(".South_America").fadeIn(450);
	        $(".Europe").fadeIn(450);
	        $(".Africa").fadeIn(450);
	        $(".Oceania").fadeIn(450);
		    $(".mudi_city").hide();
		    $(".mudi_city_ul").eq(4).fadeOut(450);
		    $(".Asia").animate({					
                "top":"186px",					
                "left":"633px"				
            },450);
            event.stopPropagation()
    })
    $(".close_box_btn").eq(5).click(function(event){
        	    	$(".North_America").fadeIn(450);
	        $(".South_America").fadeIn(450);
	        $(".Europe").fadeIn(450);
	        $(".Africa").fadeIn(450);
	        $(".Asia").fadeIn(450);
		    $(".mudi_city").hide();
		    $(".mudi_city_ul").eq(5).fadeOut(450);
		    $(".Oceania").animate({					
                "top":"359px",					
                "left":"776px"				
            },450);
            event.stopPropagation()
    })
	/******************************主特效******************************/
});